LPServer=function(){var k=null,d=null,r,s=function(a,c){var b=a,e={},m;for(m in b){var d=b[m];if("object"===typeof d)for(var g in d)e[m+"["+g+"]"]=d[g];else e[m]=d}a=e;c=c||"";var b=[],f;for(f in a)e=a[f],"object"===typeof e?b=b.concat(s(e,f)):(c&&(f=c+"["+f+"]"),b.push(f+"="+encodeURIComponent(e)));return b};r=function(a){return s(a).join("&")};var t=function(a){var c=r(a.data),b=new XMLHttpRequest;a.success&&(b.onload=function(){if(4===b.readyState)if(200===b.status)switch(a.dataType){case "xml":a.success(b.responseXML,
b.responseText);break;case "json":var c=null;try{c=JSON.parse(b.responseText)}catch(d){}a.success(c,b.responseText);break;default:a.success(b.responseText)}else a.error&&a.error(b,b.statusText)});a.error&&(b.onerror=function(){a.error(b,b.statusText)});b.open(a.type||"GET",a.url,!0);b.setRequestHeader("Content-Type","application/x-www-form-urlencoded");b.send(c)},u=function(a){return function(){a()}},g=function(a,c,b,e){j(a,c,b,e)||c.error(b)},j,v=function(a,c,b,e){return a&&(a=a[b],"function"===
typeof a)?(a(e,c),!0):!1};j=function(a,c,b,e){a=v(a,c,b,e);return a=v(c.callbacks,c,b,e)||a};var w=function(a,c){try{f.logException(a)}catch(b){}a instanceof h?c.error(a.message):c.error()},A=function(a,c){return function(b,e){try{j(a,c,e)||(null===b&&e?c.error("invalidxml"):z(b,a,c))}catch(d){w(d,c)}}},l=function(a,c){var b=a.getElementsByTagName(c);return 0<b.length?b[0]:null},n=function(a,c){var b=l(a,c);return b?b.textContent:""},z=function(a,c,b){var e=l(a,"result"),d=l(a,"ok"),f=l(a,"error"),
h=l(a,"failed");if(e){var d=e.getAttribute("rc"),f=e.getAttribute("msg"),h=e.getAttribute("success"),k=e.getAttribute("ok");if(d){g(c,b,d,e);return}if(f){g(c,b,f,e);return}if(h){g(c,b,h,e);return}if(k){g(c,b,"ok");return}e=e.textContent.trim();if("ok"===e){if(!j(c,b,"ok")){g(c,b,n(a,"status"));return}}else if("bad"===e){b.error(n(a,"message"));return}}else{if(d){g(c,b,"ok",d);return}if(f){j(c,b,f.getAttribute("cause"),f)||g(c,b,f.getAttribute("message"),f);return}if(h){g(c,b,h.getAttribute("reason"),
h);return}}"function"===typeof b.error&&b.error()},B=function(a,c){return function(b,e){try{if(null===b&&e)c.error("invalidjson");else{if(b.error){g(a,c,b.error,b);return}if(b.res){if("success"!==b.res){g(a,c,b.res,b);return}}else if(j(a,c,b.reason,b)||j(a,c,b.status,b)||j(a,c,b.cmd,b))return}if("function"===typeof a["default"])a["default"](b,c);else"function"===typeof c.success&&c.success(b)}catch(d){w(d,c)}}},p=function(a){a.userSupplied=a.userSupplied||{};a.type=void 0===a.type?"POST":a.type;a.url=
f.getBaseURL()+a.url;if(a.userSupplied.requestArgs)for(var c in a.userSupplied.requestArgs)a.data[c]=a.userSupplied.requestArgs[c];a.userSupplied.error&&(a.error=u(a.userSupplied.error));if(a.data&&void 0===a.data.token){if(null===k){c=a.userSupplied.error;f.ajax({type:"POST",url:f.getBaseURL()+"getCSRFToken.php",success:function(b){k=b;a.data.token=k;f.ajax(a)},error:u(c)});return}a.data.token=k}f.ajax(a)},x=function(a,c){if("function"!==typeof c.success&&("function"===typeof c.userSupplied.success||
"function"===typeof c.userSupplied.error))if("string"===typeof c.success){var b={};b[c.success]=c.userSupplied.success;c.success=a(b,c.userSupplied)}else c.success=a(c.callbacks,c.userSupplied)},y=function(a,c,b){b=b||[];for(var e in c){var d=a[e],f=c[e];if("object"===typeof f)y(d,f,b.concat(e));else if(typeof d!==f)throw b.push(e),"Extension is missing the following property: "+b.join(".")+" ("+f+")";}},q=function(a,c,b){a=a.getAttribute(c);return void 0===a?b:a},C={AES:{Encrypt:"function",Decrypt:"function",
hex2bin:"function"},enc:"function",dec:"function",RSAKey:"function",createRandomHexString:"function",parse_public_key:"function",enccbc:"function",make_lp_key_iterations:"function",make_lp_hash_iterations:"function"},D={RSAKey:!0},f={ajax:t,logException:function(){},hex2bin:function(){return d.AES.hex2bin.apply(d.AES,arguments)},encryptAES:function(a,c){return 0<a.length?d.AES.Encrypt({pass:c,data:a,b64:!0,bits:256}):a},decryptAES:function(a,c){return d.AES.Decrypt({pass:c,data:a,b64:!0,bits:256})},
encrypt:function(a,c){return d.enc(a,c)},decrypt:function(a,c){try{return d.dec(a,c)}catch(b){return""}},createRandomHexString:function(){return d.createRandomHexString.apply(d,arguments)},parsePublicKey:function(){return d.parse_public_key.apply(d,arguments)},encryptCBC:function(){return d.enccbc.apply(d,arguments)},makeKey:function(){return d.make_lp_key_iterations.apply(d,arguments)},makeHash:function(){return d.make_lp_hash_iterations.apply(d,arguments)},getBaseURL:function(){return d.base_url||
""},getLocalKey:function(){return d.g_local_key},setLocalKey:function(a){d.g_local_key=a}},h=function(a){this.message=a;this.stack=Error().stack};h.prototype=Object.create(Error.prototype);h.prototype.name="ClientException";h.prototype.constructor=h;return{ajax:t,getRecordsFromResponse:function(a,c,b){for(var e=[],d=0;d<b;++d)e.push(q(a,c+d));return e},jsonRequest:function(a){x(B,a);a.dataType="json";p(a)},xmlRequest:function(a){x(A,a);a.dataType="xml";p(a)},textRequest:function(a){a.dataType="text";
p(a)},initialize:function(a,c){y(a,C);for(var b in c)f[b]=c[b];for(var e in D)f[e]=a[e];d=a},ext:f,isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},getNodes:function(a,c){return a.getElementsByTagName(c)},getNode:l,getNodeText:n,getAttr:q,getAttrInt:function(a,c,b){a=parseInt(q(a,c,b));return isNaN(a)?b:a},extendCallback:function(a,c){return function(){c.apply(window,arguments);a&&a.apply(window,arguments)}},ClientException:h}}();
